<!--suppress ES6UnusedImports -->
<template>
  <div>
    <PageHeader :pagedesc="page.description" :pagetitle="page.title"></PageHeader>

    <v-card class="mt-5">
      <v-card-text>
        <!-- Display FAQ view if faq is set to true in the page frontmatter -->
        <v-expansion-panels v-if="page.faq" popout>
          <v-expansion-panel v-for="(question, index) in page.questions" :key="index">
            <v-expansion-panel-header>
              {{ question.q }}
            </v-expansion-panel-header>
            <v-expansion-panel-content>
              <p v-html="question.a">
              </p>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-expansion-panels>

        <!-- Otherwise just render the markdown -->
        <nuxt-content v-else :document="page"/>
      </v-card-text>
    </v-card>
  </div>
</template>
<script>
// Need to manually import Vuetify components, otherwise components in MD files will not load.
import { VBtn, VAlert } from 'vuetify/lib'

// This page generates a page based on content from nuxt-content CMS.
export default {
  component: true,
  async asyncData({$content, params, error}) {
    try {
      // Arguments for $content are first the directory from which the content will come (site-pages) and then the slug (autogenerated.)
      const page = await $content('site-pages', params.slug).fetch()


      return {
        page
      }
    } catch (err) {
      error({
        statusCode: 404
      })
    }
  }
}
</script>
<style>
.nuxt-content > h1 {
  margin-bottom: 15px;
}
.nuxt-content > h2 {
  margin-bottom: 15px;
}
.nuxt-content > hr {
  margin-top: 15px;
  margin-bottom: 20px !important;
}
</style>
